# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd0465a82947aa065b60ffb584b63c9564d62a70ec4437cc4e81b6f90eb40bc1e4530e19c1eca204a98ccd5f3f6974e5322d706a5a40ff1d8e84bab4f7317bd8

test:
  secret_key_base: 0a72b11bea406bf9f3437714cc301b496c10b93c4c757a44334e84d9ea9720104be670254c4ef716b1ab101548f253238ede7f7fb668622b2aa207d6265e9cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
